<a href="https://colab.research.google.com/github/Pranitha3197/Generative-AI/blob/main/LAB_QUES_(1_10).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#1Q
import numpy as np
from sklearn.metrics import mean_squared_error

# Values
y_actual = np.array([20, 30, 40, 50])
y_pred = np.array([20.5, 30.3, 40.2, 50.6])

# MSE
mse = mean_squared_error(y_actual, y_pred)

print(f"MSE: {mse:.2f}")


MSE: 0.19


In [10]:
#2Q
import numpy as np
from sklearn.metrics import mean_absolute_error

# Values
y_actual = np.array([20, 30, 40, 50])
y_pred = np.array([20.5, 30.3, 40.2, 50.6])

# MAE
mae = mean_absolute_error(y_actual, y_pred)

print(f"MAE: {mae:.2f}")

MAE: 0.40


In [11]:
#3Q
import numpy as np
from sklearn.metrics import mean_squared_error

# Values
y_actual = np.array([20, 30, 40, 50])
y_pred = np.array([20.5, 30.3, 40.2, 50.6])

# RMSE
rmse = np.sqrt(mean_squared_error(y_actual, y_pred))

print(f"RMSE: {rmse:.2f}")

RMSE: 0.43


In [1]:
#4Q
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score

# Actual and predicted values
y_actual = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
y_pred = np.array([0, 0, 1, 2, 2, 1, 0, 2, 0, 2, 0, 0, 1, 2, 2])

# Compute confusion matrix and accuracy
conf_matrix = confusion_matrix(y_actual, y_pred)
accuracy = accuracy_score(y_actual, y_pred)

print("Confusion Matrix:\n", conf_matrix)
print(f"Accuracy: {accuracy}")


Confusion Matrix:
 [[2 1 2]
 [2 1 2]
 [2 1 2]]
Accuracy: 0.3333333333333333


In [2]:
#5Q
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score

# Actual and predicted values
y_actual = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])
y_pred = np.array([0, 0, 1, 1, 0, 1, 0, 1, 0, 1])

# Compute confusion matrix and accuracy
conf_matrix = confusion_matrix(y_actual, y_pred)
accuracy = accuracy_score(y_actual, y_pred)

print("Confusion Matrix:\n", conf_matrix)
print(f"Accuracy: {accuracy}")


Confusion Matrix:
 [[3 2]
 [2 3]]
Accuracy: 0.6


In [3]:
#6Q
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score

# Actual and predicted values
y_actual = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])
y_pred = np.array([0, 0, 1, 1, 0, 1, 0, 1, 0, 1])

# Compute confusion matrix, accuracy, and precision
conf_matrix = confusion_matrix(y_actual, y_pred)
accuracy = accuracy_score(y_actual, y_pred)
precision = precision_score(y_actual, y_pred, average='macro')

print("Confusion Matrix:\n", conf_matrix)
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")


Confusion Matrix:
 [[3 2]
 [2 3]]
Accuracy: 0.6
Precision: 0.6


In [4]:
#7Q
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

# Actual and predicted values
y_actual = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])
y_pred = np.array([0, 0, 1, 1, 0, 1, 0, 1, 0, 1])

# Compute confusion matrix, accuracy, precision, and recall
conf_matrix = confusion_matrix(y_actual, y_pred)
accuracy = accuracy_score(y_actual, y_pred)
precision = precision_score(y_actual, y_pred, average='macro')
recall = recall_score(y_actual, y_pred, average='macro')

print("Confusion Matrix:\n", conf_matrix)
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")


Confusion Matrix:
 [[3 2]
 [2 3]]
Accuracy: 0.6
Precision: 0.6
Recall: 0.6


In [6]:
#8Q
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Actual and predicted values
y_actual = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])
y_pred = np.array([0, 0, 1, 1, 0, 1, 0, 1, 0, 1])

# Compute confusion matrix, accuracy, precision, recall, and F1-score
conf_matrix = confusion_matrix(y_actual, y_pred)
accuracy = accuracy_score(y_actual, y_pred)
precision = precision_score(y_actual, y_pred, average='macro')
recall = recall_score(y_actual, y_pred, average='macro')
f1 = f1_score(y_actual, y_pred, average='macro')

print("Confusion Matrix:\n", conf_matrix)
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")


Confusion Matrix:
 [[3 2]
 [2 3]]
Accuracy: 0.6
Precision: 0.6
Recall: 0.6
F1 Score: 0.6


In [7]:
#9Q
from scipy.optimize import linprog

# Coefficients for the objective function (maximize P = 4X + 5Y + 6Z)
c = [-4, -5, -6]

# Constraints
A = [[2, 1, 1], [4, 3, 0]]
b = [14, 20]

# Bounds for variables
bounds = [(0, None)] * 3

# Solve the problem
result = linprog(c, A_ub=A, b_ub=b, bounds=bounds, method='highs')

# Print results
print(f"X = {result.x[0]:.2f}, Y = {result.x[1]:.2f}, Z = {result.x[2]:.2f}")
print(f"Max P = {-result.fun:.2f}")


X = 0.00, Y = 0.00, Z = 14.00
Max P = 84.00


In [8]:
#10Q
from scipy.optimize import linprog

# Coefficients for the objective function (maximize P = 40A + 30B)
c = [-40, -30]

# Constraints
A = [[1, 2], [2, 3]]
b = [40, 60]

# Bounds for variables
bounds = [(0, None)] * 2

# Solve the problem
result = linprog(c, A_ub=A, b_ub=b, bounds=bounds, method='highs')

# Print results
print(f"A = {result.x[0]:.2f}, B = {result.x[1]:.2f}")
print(f"Max P = {-result.fun:.2f}")

A = 30.00, B = 0.00
Max P = 1200.00
